In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
%matplotlib inline

In [2]:
df= pd.read_csv("D:\\train.csv")
df.head()
df=df.dropna()

In [3]:
cdf=df[['Survived','Pclass','Sex','Age','Parch','Fare','Embarked']]
X=cdf[['Pclass','Sex','Age','Parch','Fare','Embarked']].values
X[0:5]

array([[1, 'female', 38.0, 0, 71.2833, 'C'],
       [1, 'female', 35.0, 0, 53.1, 'S'],
       [1, 'male', 54.0, 0, 51.8625, 'S'],
       [3, 'female', 4.0, 1, 16.7, 'S'],
       [1, 'female', 58.0, 0, 26.55, 'S']], dtype=object)

In [4]:
s=preprocessing.LabelEncoder()
s.fit(['male','female'])
X[:,1]=s.transform(X[:,1])
X[0:5]


array([[1, 0, 38.0, 0, 71.2833, 'C'],
       [1, 0, 35.0, 0, 53.1, 'S'],
       [1, 1, 54.0, 0, 51.8625, 'S'],
       [3, 0, 4.0, 1, 16.7, 'S'],
       [1, 0, 58.0, 0, 26.55, 'S']], dtype=object)

In [53]:
Embarked=preprocessing.LabelEncoder()
Embarked.fit(['S','C','Q'])
X[:,5]=Embarked.transform(X[:,5])
X[0:5]

array([[3, 'male', 34.5, 0, 7.8292, 1],
       [3, 'female', 47.0, 0, 7.0, 2],
       [2, 'male', 62.0, 0, 9.6875, 1],
       [3, 'male', 27.0, 0, 8.6625, 2],
       [3, 'female', 22.0, 1, 12.2875, 2]], dtype=object)

In [6]:
y=cdf['Survived']
y[0:5].values

array([1, 1, 0, 1, 1], dtype=int64)

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)
print('TrainSet:',X.shape,y.shape)

TrainSet: (183, 6) (183,)


In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
model=RandomForestClassifier()
model.fit(X_train,y_train)
yhat=model.predict(X_test)
acc=metrics.accuracy_score(y_test,yhat)
print("ACCURACY :" , acc)

ACCURACY : 0.8648648648648649


C:\Users\ASHINONU\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [57]:
sdf=pd.read_csv("D:\\test.csv")
sdf.head()
sdf=sdf.dropna()

In [58]:
scdf=sdf[['Pclass','Sex','Age','Parch','Fare','Embarked']]
X=scdf[['Pclass','Sex','Age','Parch','Fare','Embarked']].values
X[0:5]

array([[1, 'female', 23.0, 0, 82.2667, 'S'],
       [1, 'female', 47.0, 0, 61.175, 'S'],
       [1, 'female', 48.0, 3, 262.375, 'C'],
       [1, 'female', 22.0, 1, 61.9792, 'C'],
       [1, 'male', 41.0, 0, 30.5, 'S']], dtype=object)

In [59]:
X[:,1]=s.transform(X[:,1])
X[0:5]


array([[1, 0, 23.0, 0, 82.2667, 'S'],
       [1, 0, 47.0, 0, 61.175, 'S'],
       [1, 0, 48.0, 3, 262.375, 'C'],
       [1, 0, 22.0, 1, 61.9792, 'C'],
       [1, 1, 41.0, 0, 30.5, 'S']], dtype=object)

In [60]:
X[:,5]=Embarked.transform(X[:,5])
X[0:5]

array([[1, 0, 23.0, 0, 82.2667, 2],
       [1, 0, 47.0, 0, 61.175, 2],
       [1, 0, 48.0, 3, 262.375, 0],
       [1, 0, 22.0, 1, 61.9792, 0],
       [1, 1, 41.0, 0, 30.5, 2]], dtype=object)

In [61]:
survived=model.predict(X)
sdf["Survived"]=survived
sdf.head()

PassengerId  Pclass                                               Name  \
12          904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
14          906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
24          916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
26          918       1                       Ostby, Miss. Helene Ragnhild   
28          920       1                            Brady, Mr. John Bertram   

       Sex   Age  SibSp  Parch       Ticket      Fare            Cabin  \
12  female  23.0      1      0        21228   82.2667              B45   
14  female  47.0      1      0  W.E.P. 5734   61.1750              E31   
24  female  48.0      1      3     PC 17608  262.3750  B57 B59 B63 B66   
26  female  22.0      0      1       113509   61.9792              B36   
28    male  41.0      0      0       113054   30.5000              A21   

   Embarked  Survived  
12        S         1  
14        S         1  
24        C         1  
26        C         1  
28        S         0